# Generated by Django 3.2.18 on 2023-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
    ]
